<?php

return  [
  'DEX' =>  [
    'name' => 'Nop Goliat Airport',
    'city' => 'Dekai Yahukimo',
  ],
  'PPJ' =>  [
    'name' => 'Pulau Panjang Airport',
    'city' => 'Jakarta',
  ],
  'JBB' =>  [
    'name' => 'Noto Hadinegoro, Jember Airport',
    'city' => 'Jember',
  ],
  'BWX' =>  [
    'name' => 'Blimbingsari Airport',
    'city' => 'Banyuwangi',
  ],
  'AAP' =>  [
    'name' => 'Aji Pangeran Tumenggung Pranoto International Airport',
    'city' => 'Samarinda',
  ],
  'BXW' =>  [
    'name' => 'Bawean Airport',
    'city' => 'Bawean',
  ],
  'AAS' =>  [
    'name' => 'Apalapsili Airport',
    'city' => 'Apalapsili',
  ],
  'AGD' =>  [
    'name' => 'Anggi Airport',
    'city' => 'Anggi Papua Island',
  ],
  'AKQ' =>  [
    'name' => 'Gunung Batin Airport',
    'city' => 'Astraksetra Sumatra Island',
  ],
  'AYW' =>  [
    'name' => 'Ayawasi Airport',
    'city' => 'Ayawasi Papua Island',
  ],
  'BJG' =>  [
    'name' => 'Boalang Airport',
    'city' => 'Boalang Celebes Island',
  ],
  'BXM' =>  [
    'name' => 'Batom Airport',
    'city' => 'Batom Papua Island',
  ],
  'DRH' =>  [
    'name' => 'Dabra Airport',
    'city' => 'Dabra Papua Island',
  ],
  'ELR' =>  [
    'name' => 'Elelim Airport',
    'city' => 'Elelim Papua Island',
  ],
  'EWE' =>  [
    'name' => 'Ewer Airport',
    'city' => 'Asmat',
  ],
  'FOO' =>  [
    'name' => 'Kornasoren Airfield',
    'city' => 'Kornasoren Numfoor Island',
  ],
  'GAV' =>  [
    'name' => 'Gag Island Airport',
    'city' => 'Gag Island',
  ],
  'IUL' =>  [
    'name' => 'Ilu Airport',
    'city' => 'Ilu Papua Island',
  ],
  'KBF' =>  [
    'name' => 'Karubaga Airport',
    'city' => 'Karubaga Papua Island',
  ],
  'KBX' =>  [
    'name' => 'Kambuaya Airport',
    'city' => 'Kambuaya Papua Island',
  ],
  'KCD' =>  [
    'name' => 'Kamur Airport',
    'city' => 'Kamur Papua Island',
  ],
  'KEA' =>  [
    'name' => 'Keisah Airport',
    'city' => 'Keisah Papua Island',
  ],
  'KMM' =>  [
    'name' => 'Kimaam Airport',
    'city' => 'Kimaam',
    'keys' => [
  'Taman Nasional Wasur',
  'Pantai Lampu Satu',
  'Tugu Lingkaran Brawijaya',
  'Tugu Pepera',
  'Pantai Payum',
  'Pantai Wisata Onggaya',
  'Lotus Garden',
  'Tugu 0 Km Sabang-Merauke',
  'Tugu L B Moerdani',
  'Pulau Habe',
  'Rumah Rayap Musamus',
  'Pantai Okaba'
    ]
  ],
  'KOD' =>  [
    'name' => 'Kotabangun Airport',
    'city' => 'Kotabangun Borneo Island',
  ],
  'KRC' =>  [
    'name' => 'Departi Parbo Airport',
    'city' => 'Sungai Penuh',
  ],
  'KWB' =>  [
    'name' => 'Dewadaru Kemujan Island',
    'city' => 'Karimunjawa',
    'keys' => [
  'Baturaden Banyumas',
  'Candi Borobudur',
  'Kampung Batik',
  'Museum Kereta',
  'Museum Purbakala Sangiran',
  'Dataran Tinggi Dieng',
  'Kedung Ombo',
  'Museum R.A. Kartini',
  'Keraton Kasunanan Surakarta Hadiningrat',
  'Pasar Malam Ngarsopuro',
  'Goa Jatijajar',
  'Taman Nasional Karimunjawa',
  'Ketep Pass',
  'Air Terjun Montel',
  'Rafting Sungai Progo Atas',
  'Pantai Petanahan',
  'Pemandian Air Panas Krakal',
  'Teluk Penyu',
  'Pantai Suwuk',
  'Benteng Vander Wijck',
  'Gunung Slamet',
  'Batur Agung',
  'Pemandian Tirta Husada Kali Bacin',
  'Gua Maria Kaliori',
  'Monumen Panglima Besar Jenderal Sudirman',
  'Telaga Pucung',
  'Curug Cipendok',
  'Tawangmangu',
  'Air Terjun Jumog',
  'Kampung Batik Kauman',
  'Masjid Agung Jawa Tengah',
  'Museum Ronggowarsito',
  'Air Terjun Kali Pancur'
    ]
  ],
  'LLN' =>  [
    'name' => 'Kelila Airport',
    'city' => 'Kelila Papua Island',
  ],
  'LWE' =>  [
    'name' => 'Lewoleba Airport',
    'city' => 'Lewoleba Lembata Island',
  ],
  'LYK' =>  [
    'name' => 'Lunyuk Airport',
    'city' => 'Lunyuk Simbawa Island',
  ],
  'MJY' =>  [
    'name' => 'Mangunjaya Airport',
    'city' => 'Mangungaya Sumatra Island',
  ],
  'MPT' =>  [
    'name' => 'Maliana airport',
    'city' => 'Maliana Alor Island',
  ],
  'MSI' =>  [
    'name' => 'Masalembo Airport',
    'city' => 'Masalembo Island',
  ],
  'MUF' =>  [
    'name' => 'Muting Airport',
    'city' => 'Muting',
  ],
  'NAF' =>  [
    'name' => 'Banaina Airport',
    'city' => 'Banaina Borneo Island',
  ],
  'OBD' =>  [
    'name' => 'Obano Airport',
    'city' => 'Obano Papua Island',
  ],
  'PUM' =>  [
    'name' => 'Pomala Airport',
    'city' => 'Kolaka',
  ],
  'PWL' =>  [
    'name' => 'Purwokerto Airport',
    'city' => 'Purwokerto Java Island',
  ],
  'RAQ' =>  [
    'name' => 'Sugimanuru Airport',
    'city' => 'Raha Muna Island',
  ],
  'RKI' =>  [
    'name' => 'Rokot Airport',
    'city' => 'Rokot Sumatra Island',
  ],
  'RTI' =>  [
    'name' => 'David Constantijn Saudale Airport',
    'city' => 'Rote Island',
    'keys' => [
  'Tangga 300',
  'Batu Termanu',
  'Pantai Mulut Seribu',
  'Pantai Nembrala',
  'Pulau Doo',
  'Mata Air Oemau',
  'Pantai Tolanamon',
  'Pulau Ndana',
  'Bukit Bebalain',
  'Danau Laut Mati',
  'Pantai Boa',
  'Pantai Laviti',
  'Pemandian Sulimatan',
  'Pantai Tiang Bendera'
    ]
  ],
  'RUF' =>  [
    'name' => 'Yuruf Airport',
    'city' => 'Amgotro',
  ],
  'RZS' =>  [
    'name' => 'Sawan Airport',
    'city' => 'Sawan Bali Island',
  ],
  'SAE' =>  [
    'name' => 'Sangir Airport',
    'city' => 'Sangir Simbawa Island',
  ],
  'TBM' =>  [
    'name' => 'Tumbang Samba Airport',
    'city' => 'Tumbang Samba Borneo Island',
  ],
  'TMY' =>  [
    'name' => 'Tiom Airport',
    'city' => 'Tiom Papua Island',
  ],
  'ZEG' =>  [
    'name' => 'Senggo Airport',
    'city' => 'Senggo Papua Island',
  ],
  'UGU' =>  [
    'name' => 'Bilogai Sugapa Airport',
    'city' => 'Sugapa Papua Island',
  ],
  'JIO' =>  [
    'name' => 'Jos Orno Imsula Airport',
    'city' => 'Tiakur',
  ],
  'MOH' =>  [
    'name' => 'Maleo Airport',
    'city' => 'Morowali',
  ],
  'NKD' =>  [
    'name' => 'Sinak Airport',
    'city' => 'Sinak',
  ],
  'TQQ' =>  [
    'name' => 'Maranggo Airport',
    'city' => 'Waha Tomea Island',
  ],
  'UPG' =>  [
    'name' => 'Hasanuddin International Airport',
    'city' => 'Ujung Pandang Celebes Island',
    'keys' => [
  'Pantai Losari',
  'Pantai Akkarena',
  'Trans Studio Makassar',
  'Pemandian Air Panas Lejja',
  'Taman Nasional Banti Murung di Makassar',
  'Pulau Kapoposang',
  'Pulau Gusung',
  'Pulau Kayangan',
  'Pulau Lae-Lae',
  'Pulau Kodingareng Keke',
  'Pulau Bulupoloe',
  'Pulau Dutungan',
  'Pulau Samalona',
  'Tanjung Bira',
  'Taman Laut Takabonerate',
  'Pegunungan Karst',
  'Air Terjun Takapala',
  'Danau Tempe',
  'Desa Wisata Lakkang',
  'Malino',
  'Benteng Ujung Pandang',
  'Benteng Somba Opu',
  'Museum Balla Lompoa',
  'Kawasan Adat Ammatoa',
  'Ke\'te Kesu',
  'Pusat Kerajinan Perahu Phinisi'
    ]
  ],
  'MJU' =>  [
    'name' => 'Tampa Padang Airport',
    'city' => 'Mamuju Celebes Island',
  ],
  'BIK' =>  [
    'name' => 'Frans Kaisiepo Airport',
    'city' => 'Biak Supiori Island',
  ],
  'ONI' =>  [
    'name' => 'Moanamani Airport',
    'city' => 'Moanamani Papua Island',
  ],
  'WET' =>  [
    'name' => 'Wagethe Airport',
    'city' => 'Wagethe Papua Island',
  ],
  'NBX' =>  [
    'name' => 'Nabire Airport',
    'city' => 'Nabire Papua Island',
  ],
  'ILA' =>  [
    'name' => 'Illaga Airport',
    'city' => 'Illaga Papua Island',
  ],
  'KOX' =>  [
    'name' => 'Kokonau Airport',
    'city' => 'Kokonau Papua Island',
  ],
  'ZRI' =>  [
    'name' => 'Serui Airport',
    'city' => 'Serui Japen Island',
  ],
  'TIM' =>  [
    'name' => 'Moses Kilangin Airport',
    'city' => 'Timika Papua Island',
  ],
  'EWI' =>  [
    'name' => 'Enarotali Airport',
    'city' => 'Enarotali Papua Island',
  ],
  'AMI' =>  [
    'name' => 'Selaparang Airport',
    'city' => 'Mataram Lombok Island',
  ],
  'BMU' =>  [
    'name' => 'Muhammad Salahuddin Airport',
    'city' => 'Bima Sumbawa Island',
  ],
  'DPS' =>  [
    'name' => 'Ngurah Rai [Bali] International Airport',
    'city' => 'Denpasar Bali Island',
    'keys' => [
  'Bukit Campuhan',
  'Pantai Pandawa',
  'Waterbom Bali',
  'Garuda Wisnu Kencana',
  'Pantai Kuta',
  'Pura Besakih',
  'Bali Bird Park',
  'Bali Safari',
  'Marine Park',
  'Pantai Sanur',
  'Pantai Uluwatu',
  'Monkey Forest Ubud',
  'Desa Penglipuran',
  'Danau Batur',
  'Pantai Lovina',
  'Pantai Melasti',
  'Taman Nasional Bali Barat',
  'Danau Beratan',
  'Danau Tamblingan',
  'Pantai Tegal Wangi',
  'Pantai Seminyak',
  'Pantai Canggu',
  'Pasar Sukawati',
  'Pura Uluwatu',
  'Gunung Batur',
  'Elephant Safari Park',
  'Tanah Lot',
  'Pantai Amed',
  'Museum Blanco',
  'Kebun Raya Bedugul',
  'Nusa Penida',
  'Pantai Gunung Payung',
  'Nusa Lembongan',
  'Tirta Empul',
  'Pura Lempuyang',
  'Air Terjun Blangsinga',
  'Pantai Balangan',
  'Goa Gajah'
    ]
  ],
  'LOP' =>  [
    'name' => 'Lombok International Airport',
    'city' => 'Mataram',
  ],
  'SWQ' =>  [
    'name' => 'Sumbawa Besar Airport',
    'city' => 'Sumbawa Island',
  ],
  'TMC' =>  [
    'name' => 'Tambolaka Airport',
    'city' => 'Waikabubak Sumba Island',
  ],
  'WGP' =>  [
    'name' => 'Umbu Mehang Kunda Airport',
    'city' => 'Waingapu Sumba Island',
  ],
  'LLO' =>  [
    'name' => 'Bua Airport',
    'city' => 'Palopo',
  ],
  'YIA' =>  [
    'name' => 'Yogyakarta International Airport',
    'city' => 'Yogyakarta',
    'keys' => [
  'Pantai Indrayanti',
  'Pantai Nglambor',
  'Pantai Pok Tunggal',
  'Jalan Malioboro',
  'Pasar Beringharjo',
  'Benteng Vredeburg Yogyakarta',
  'Museum Ullen Sentalu',
  'Keraton Yogyakarta',
  'Taman Sari Jogja',
  'Museum Gunung Merapi',
  'Pantai Parangtritis',
  'Goa Jomblang',
  'Goa Pindul',
  'Candi Ratu Boko',
  'Kebun Buah Mangunan',
  'Pantai Depok',
  'Pantai Depok Laguna',
  'Pantai Sundak',
  'Hutan Mangrove Kulon Progo',
  'Jogja Bay Pirates Adventure Waterpark',
  'Air Terjun Kedung Pedut',
  'Tebing Breksi',
  'Kalibiru Di Kulon Progo',
  'Pantai Sepanjang',
  'Pantai Goa Cemara',
  'Pantai Glagah',
  'Pantai Krakal',
  'Pantai Siung',
  'Puncak Becici',
  'Pantai Sadranan',
  'Sindu Kusuma Edupark',
  'Bukit Bintang Jogja',
  'Hutan Pinus Pengger',
  'Bukit Panguk Kediwung',
  'Pantai Nguluran',
  'Pantai Samas',
  'Pantai Drini',
  'Pantai Timang',
  'Pantai Kukup',
  'Pantai Ngobaran',
  'Merapi Park',
  'Air Terjun Sri Gethuk',
  'Candi Sewu',
  'Pantai Wediombo',
  'Taman Pintar Yogyakarta',
  'Pantai Jogan'
    ]
  ],
  'ARJ' =>  [
    'name' => 'Arso Airport',
    'city' => 'Arso Papua Island',
  ],
  'BUI' =>  [
    'name' => 'Bokondini Airport',
    'city' => 'Bokondini',
  ],
  'ZRM' =>  [
    'name' => 'Sarmi Airport',
    'city' => 'Sarmi Papua Island',
  ],
  'DJJ' =>  [
    'name' => 'Sentani International Airport',
    'city' => 'Jayapura Papua Island',
  ],
  'LHI' =>  [
    'name' => 'Lereh Airport',
    'city' => 'Lereh Papua Island',
  ],
  'LII' =>  [
    'name' => 'Mulia Airport',
    'city' => 'Mulia Papua Island',
  ],
  'OKL' =>  [
    'name' => 'Oksibil Airport',
    'city' => 'Oksibil Papua Island',
  ],
  'WAR' =>  [
    'name' => 'Waris Airport',
    'city' => 'Swach',
  ],
  'SEH' =>  [
    'name' => 'Senggeh Airport',
    'city' => 'Senggeh',
  ],
  'UBR' =>  [
    'name' => 'Ubrub Airport',
    'city' => 'Ubrub Papua Island',
  ],
  'WMX' =>  [
    'name' => 'Wamena Airport',
    'city' => 'Wamena Papua Island',
  ],
  'MDP' =>  [
    'name' => 'Mindiptana Airport',
    'city' => 'Mindiptana Papua Island',
  ],
  'BXD' =>  [
    'name' => 'Bade Airport',
    'city' => 'Bade',
  ],
  'MKQ' =>  [
    'name' => 'Mopah Airport',
    'city' => 'Merauke Papua Island',
  ],
  'OKQ' =>  [
    'name' => 'Okaba Airport',
    'city' => 'Okaba Papua Island',
  ],
  'KEI' =>  [
    'name' => 'Kepi Airport',
    'city' => 'Kepi Papua Island',
  ],
  'TMH' =>  [
    'name' => 'Tanah Merah Airport',
    'city' => 'Tanah Merah Papua Island',
  ],
  'TJS' =>  [
    'name' => 'Tanjung Harapan Airport',
    'city' => 'Tanjung Selor Borneo Island',
  ],
  'DTD' =>  [
    'name' => 'Datadawai Airport',
    'city' => 'Datadawai Borneo Island',
  ],
  'BEJ' =>  [
    'name' => 'Kalimarau Airport',
    'city' => 'Tanjung Redeb Borneo Island',
  ],
  'BPN' =>  [
    'name' => 'Sultan Aji Muhamad Sulaiman Airport',
    'city' => 'Kotamadya Balikpapan',
    'keys' => [
  'Pantai Melawai',
  'Pantai Lamaru',
  'Pantai Kemala',
  'Pantai Manggar Segarasari',
  'Pantai Banua Patra',
  'Pantai Monpera',
  'Pantai Sepinggan',
  'Caribbean Island Waterpark',
  'Aquaboom BSB',
  'Wisata Alam Hutan Bakau Margomulyo',
  'Wisata Alam Hutan Lindung Sungai Wain',
  'Penangkaran Buaya Teritip',
  'Kampung Atas Air Margasari',
  'Danau Cermin Lamaru',
  'Danau Manggar',
  'Waduk Manggar',
  'Kebun Raya Balikpapan',
  'Taman Bekapai',
  'Dohor Heritage'
    ]
  ],
  'TRK' =>  [
    'name' => 'Juwata Airport',
    'city' => 'Tarakan Island',
  ],
  'TSX' =>  [
    'name' => 'Tanjung Santan Airport',
    'city' => 'Santan Borneo Island',
  ],
  'BYQ' =>  [
    'name' => 'Bunyu Airport',
    'city' => 'Bunju Island',
  ],
  'GLX' =>  [
    'name' => 'Gamarmalamo Airport',
    'city' => 'Galela Celebes Island',
  ],
  'PGQ' =>  [
    'name' => 'Buli Airport',
    'city' => 'Pekaulang',
  ],
  'GTO' =>  [
    'name' => 'Jalaluddin Airport',
    'city' => 'Gorontalo Celebes Island',
  ],
  'NAH' =>  [
    'name' => 'Naha Airport',
    'city' => 'Tahuna Sangihe Island',
  ],
  'TLI' =>  [
    'name' => 'Sultan Bantilan Airport',
    'city' => 'Toli Toli Celebes Island',
  ],
  'GEB' =>  [
    'name' => 'Gebe Airport',
    'city' => 'Gebe Island',
  ],
  'KAZ' =>  [
    'name' => 'Kao Airport',
    'city' => 'Kao Celebes Island',
  ],
  'PLW' =>  [
    'name' => 'Mutiara Airport',
    'city' => 'Palu Celebes Island',
  ],
  'MDC' =>  [
    'name' => 'Sam Ratulangi Airport',
    'city' => 'Manado Celebes Island',
    'keys' => [
  'Pulau Siladen',
  'Jembatan Soekarno',
  'Batu Dinding Kilo Tiga Amurang',
  'Pulau Manado Tua',
  'Rumah Alam Manado Adventure Park',
  'Pasir Timbul Nain Bunaken',
  'Pantai Patokan',
  'Pulau Lihaga',
  'Pantai Pulisan',
  'Gunung Tumpa',
  'Taman Laut Tumbak',
  'Air Terjun Kima Atas',
  'Air Terjun Tapahan Telu',
  'Tree House Puncak Urongo',
  'Taman bawah laut Bunaken',
  'Air Terjun Ratahan Telu'
    ]
  ],
  'MNA' =>  [
    'name' => 'Melangguane Airport',
    'city' => 'Karakelong Island',
  ],
  'PSJ' =>  [
    'name' => 'Kasiguncu Airport',
    'city' => 'Poso Celebes Island',
  ],
  'OTI' =>  [
    'name' => 'Pitu Airport',
    'city' => 'Gotalalamo Morotai Island',
  ],
  'TTE' =>  [
    'name' => 'Sultan Babullah Airport',
    'city' => 'Sango Ternate Island',
  ],
  'LUW' =>  [
    'name' => 'Syukuran Aminuddin Amir Airport',
    'city' => 'Luwok Celebes Island',
  ],
  'UOL' =>  [
    'name' => 'Buol Airport',
    'city' => 'Buol Celebes Island',
  ],
  'BTW' =>  [
    'name' => 'Batu Licin Airport',
    'city' => 'Batu Licin Borneo Island',
  ],
  'PKN' =>  [
    'name' => 'Iskandar Airport',
    'city' => 'Pangkalanbun Borneo Island',
  ],
  'KBU' =>  [
    'name' => 'Gusti Syamsir Alam Airport',
    'city' => 'Stagen Laut Island',
    'keys' => [
  'Pulau Samber Gelap',
  'Pantai Teluk Tamiang',
  'Pulau Tanjung Kunyit',
  'Pulau Denawan',
  'Pulau Pamalikan',
  'Pulau Birah-Birahan',
  'Pantai Tanjung Ketapang',
  'Pantai Gedambaan',
  'Pantai Teluk Gosong',
  'Goa Temuluang'
    ]
  ],
  'TJG' =>  [
    'name' => 'Warukin Airport',
    'city' => 'Tanta Tabalong Borneo Island',
  ],
  'BDJ' =>  [
    'name' => 'Syamsudin Noor Airport',
    'city' => 'Banjarmasin Borneo Island',
  ],
  'PKY' =>  [
    'name' => 'Tjilik Riwut Airport',
    'city' => 'Palangkaraya Kalimantan Tengah',
  ],
  'SMQ' =>  [
    'name' => 'Sampit[Hasan] Airport',
    'city' => 'Sampit Borneo Island',
  ],
  'AHI' =>  [
    'name' => 'Amahai Airport',
    'city' => 'Amahai Seram Island',
  ],
  'NDA' =>  [
    'name' => 'Bandanaira Airport',
    'city' => 'Banda Naira Island',
  ],
  'DOB' =>  [
    'name' => 'Rar Gwamar Airport',
    'city' => 'Dobo Warmar Island',
  ],
  'MAL' =>  [
    'name' => 'Mangole Airport, Falabisahaya',
    'city' => 'Mangole Island',
  ],
  'NRE' =>  [
    'name' => 'Namrole Airport',
    'city' => 'Namrole Buru Island',
  ],
  'LAH' =>  [
    'name' => 'Oesman Sadik Airport',
    'city' => 'Labuha Halmahera Island',
  ],
  'SXK' =>  [
    'name' => 'Saumlaki Olilit Airport',
    'city' => 'Saumlaki Yamdena Island',
  ],
  'BJK' =>  [
    'name' => 'Nangasuri Airport',
    'city' => 'Maikoor Island',
  ],
  'LUV' =>  [
    'name' => 'Dumatumbun Airport',
    'city' => 'Langgur Seram Island',
  ],
  'SQN' =>  [
    'name' => 'Emalamo Sanana Airport',
    'city' => 'Sanana Seram Island',
  ],
  'AMQ' =>  [
    'name' => 'Pattimura Airport, Ambon',
    'city' => 'Ambon',
  ],
  'NAM' =>  [
    'name' => 'Namlea Airport',
    'city' => 'Namlea Buru Island',
  ],
  'TAX' =>  [
    'name' => 'Taliabu Island Airport',
    'city' => 'Tikong Taliabu Island',
  ],
  'WBA' =>  [
    'name' => 'Wahai,Seram Island',
    'city' => 'Seram Island',
  ],
  'MLG' =>  [
    'name' => 'Abdul Rachman Saleh Airport',
    'city' => 'Malang Java Island',
  ],
  'CPF' =>  [
    'name' => 'Ngloram Airport',
    'city' => 'Tjepu Java Island',
  ],
  'JOG' =>  [
    'name' => 'Adi Sutjipto International Airport',
    'city' => 'Yogyakarta Java Island',
  ],
  'SOC' =>  [
    'name' => 'Adi Sumarmo Wiryokusumo Airport',
    'city' => 'Sukarata[Solo] Java Island',
  ],
  'SUB' =>  [
    'name' => 'Juanda International Airport',
    'city' => 'Surabaya',
    'keys' => [
  'Hutan Mangrove Wonorejo',
  'Taman Bungkul',
  'Taman Flora Kebun Bibit',
  'Taman Pelangi',
  'Taman Ekspresi',
  'Taman Mundu',
  'Jembatan Suramadu',
  'Taman Angsa Pakuwon City',
  'Kenjeran Park',
  'Pakuwon Food Festival',
  'Surabaya Carnival Night Market',
  'Heerlijk Library Cafe',
  'De Mata Trick Eye Museum',
  'Ciputra Waterpark',
  'Kawasan Kota Tua surabaya',
  'Pantai Kenjeran',
  'Pecinan Tambak Bayan',
  'Masjid Cheng Ho',
  'Monumen Jalesveva Jayamahe',
  'Kebun Bambu Keputih',
  'Makam Sunan Ampel',
  'Kampung Arab',
  'Taman Sakura Keputih',
  'Jembatan Kenjeran',
  'Air Mancur Menari',
  'Wisata Pelabuhan North Quay',
  'Kebun Binatang Surabaya',
  'Gereja Kepanjen',
  'Museum Sepuluh November',
  'Masjid Al-Akbar',
  'Monumen Bambu Runcing',
  'Museum Surabaya',
  'Kebun Bibit Wonorejo',
  'Keraton Surabaya',
  'Perpustakaan Bank Indonesia',
  'Patung Sura dan Buaya',
  'Arca Joko Dolog',
  'Patung Budha Empat Rupa',
  'Taman Gantung Surabaya',
  'Monumen Kapal Selam',
  'Gelora Bung Tomo Stadium',
  'Citraland Surabaya',
  'Tugu Pahlawan Surabaya',
  'Atlantis Land Surabaya',
  'Taman Balai Kota Surabaya',
  'Dipo Lokomotif Sidotopo',
  'Taman Apsari',
  'Jembatan Merah',
  'Wisata Rumah Batik',
  'Wisata Taman Mayangkara',
  'Museum Kesehatan Dr Adhyatma'
    ]
  ],
  'SRG' =>  [
    'name' => 'Achmad Yani Airport',
    'city' => 'Semarang Java Island',
  'Wisata Lembah Kalipancur',
  'Jembatan Harapan',
  'Hutan Pinus Kragilan Magelang',
  'Waduk Pendidikan Diponegoro',
  'Waduk Jatibarang',
  'Hutan Wisata Pengaron',
  'Mangrove EduPark Pantai Maron',
  'Pantai Baruna',
  'Kolam Renang Tirto Argo Siwarak',
  'Kawasan Wisata Umbul Sidomukti',
  'Lawang Sewu',
  'Kelenteng Sam Poo Kong',
  'Kota Lama',
  'Taman Srigunting',
  'Vihara Buddhagaya Watugong',
  'Kompleks Pecinan',
  'Gereja Blenduk',
  'Kawasan Simpang Lima',
  'Tugu Muda',
  'Jalan Pahlawan',
  'Taman Tabanas',
  'Pelabuhan Tanjung Mas',
  'Kampung Pelangi',
  'Kampung Tematik',
  'Kampung Batik',
  'Old City 3D Trick Art Museum',
  'Contemporary Art Gallery',
  'Taman KB',
  'Mangrove Tapak',
  'Water Blaster',
  'Goa Kreo',
  'Pantai Marina',
  'Brown Canyon',
  'Museum Rekor Indonesia',
  'Kebun Durian dan Wisata Edukasi Watu Simbar',
  'Gunung Telomoyo',
  'Bukit Gombel',
  'Setiya Aji Flower Farm',
  'Umbul Songo Kopeng',
  'Masjid Agung',
  'Watu Gunung',
  'Pantai Tirang',
  'Air Terjun Semirang',
  'Desa Wisata Kandri'
  ],
  'SUP' =>  [
    'name' => 'Trunojoyo Airport',
    'city' => 'Sumenep Madura Island',
  ],
  'NTI' =>  [
    'name' => 'Stenkol Airport',
    'city' => 'Bintuni',
  ],
  'RSK' =>  [
    'name' => 'Abresso Airport',
    'city' => 'Ransiki Papua Island',
  ],
  'KEQ' =>  [
    'name' => 'Kebar Airport',
    'city' => 'Kebar Papua Island',
  ],
  'FKQ' =>  [
    'name' => 'Fakfak Airport',
    'city' => 'Fakfak Papua Island',
  ],
  'INX' =>  [
    'name' => 'Inanwatan Airport',
    'city' => 'Inanwatan Airport Papua Island',
  ],
  'KNG' =>  [
    'name' => 'Kaimana Airport',
    'city' => 'Kaimana Papua Island',
  ],
  'RDE' =>  [
    'name' => 'Merdei Airport',
    'city' => 'Merdei Papua Island',
  ],
  'BXB' =>  [
    'name' => 'Babo Airport',
    'city' => 'Babo Papua Island',
  ],
  'MKW' =>  [
    'name' => 'Rendani Airport',
    'city' => 'Manokwari Papua Island',
  ],
  'TXM' =>  [
    'name' => 'Teminabuan Airport',
    'city' => 'Atinjoe Papua Island',
  ],
  'WSR' =>  [
    'name' => 'Wasior Airport',
    'city' => 'Wasior Papua Island',
  ],
  'BJW' =>  [
    'name' => 'Bajawa Soa Airport',
    'city' => 'Bajawa',
  ],
  'MOF' =>  [
    'name' => 'Maumere[Wai Oti] Airport',
    'city' => 'Maumere Flores Island',
  ],
  'ENE' =>  [
    'name' => 'Ende [H Hasan Aroeboesman] Airport',
    'city' => 'Ende Flores Island',
  ],
  'RTG' =>  [
    'name' => 'Frans Sales Lega Airport',
    'city' => 'Satar Tacik Flores Island',
  ],
  'ARD' =>  [
    'name' => 'Mali Airport',
    'city' => 'Alor Island',
    'keys' => [
  'Pulau Pura',
  'Pantai Tiga Warna Puntaru',
  'Pantai Deere',
  'Pantai Mali',
  'Taman Laut Pantar',
  'Pulau Kepa',
  'Kolam Bidadari',
  'Air Mancur Tuti Adagae',
  'Desa Takpala',
  'Pantai Batu Putih',
  'Pantai Ling al',
  'Pantai Welolo',
  'Pulau Rusa',
  'Air Terjun Mataru',
  'Museum 1000 Moko'
    ]
  ],
  'LBJ' =>  [
    'name' => 'Komodo Airport',
    'city' => 'Labuan Bajo Flores Island',
  ],
  'KOE' =>  [
    'name' => 'El Tari Airport',
    'city' => 'Kupang Timor Island',
  ],
  'BUW' =>  [
    'name' => 'Betoambari Airport',
    'city' => 'Bau Bau Butung Island',
  ],
  'KSR' =>  [
    'name' => 'Selayar Aroepala Airport',
    'city' => 'Benteng',
  ],
  'MXB' =>  [
    'name' => 'Andi Jemma Airport',
    'city' => 'Masamba Celebes Island',
  ],
  'SQR' =>  [
    'name' => 'Soroako Airport',
    'city' => 'Soroako Celebes Island',
  ],
  'TTR' =>  [
    'name' => 'Pongtiku Airport',
    'city' => 'Makale',
  ],
  'KDI' =>  [
    'name' => 'Wolter Monginsidi Airport',
    'city' => 'Kendari Celebes Island',
  ],
  'SOQ' =>  [
    'name' => 'Dominique Edward Osok Airport',
    'city' => 'Sorong Papua Island',
  ],
  'CJN' =>  [
    'name' => 'Nusawiru Airport',
    'city' => 'Cijulang',
  ],
  'PKU' =>  [
    'name' => 'Sultan Syarif Kasim Ii [Simpang Tiga] Airport',
    'city' => 'Pekanbaru Sumatra Island',
    'keys' => [
  'Masjid Agung An-Nur',
  'Perpustakan Soeman HS',
  'Taman Wisata Alam Mayang',
  'Wahana Alam Mayang',
  'Masjid Raudhatul Jannah',
  'Labersa Waterpark',
  'Jembatan Siak III',
  'Stadion Utama Riau',
  'Danau Universitas Riau',
  'Danau Buatan Khayangan',
  'Air Mancur Taman Andam Dewi',
  'Lapangan Pasir Bengkalis',
  'Teluk Rhu Rupat',
  'Pantai Sepahat',
  'Pantai Selat Baru',
  'Pantai Tenggayun',
  'Pantai Lapin',
  'Pantai Marina',
  'Pantai Jangkang',
  'Pulau Beting Aceh',
  'Pantai Tanjung Medang',
  'Mangrove Sebauk',
  'Makam Datuk Laksamana Raja Dilaut',
  'Pelabuhan Bandar Sri Laksamana Bengkalis',
  'Taman Batu Ampar',
  'Masjid Istiqomah Bengkalis',
  'Pantai Purnama',
  'Pantai Teluk Makmur',
  'Pantai Teluk Makmur',
  'Taman Bukit Gelanggang',
  'Tugu Lancang Kuning',
  'Danau Bunga Tujuh',
  'Hutan Wisata Dumai',
  'Hutan Mangrove Dumai',
  'Masjid Agung Al-Manan',
  'Taman Telaga Tirta Bukit Datuk',
  'Bandar bakau',
  'Istana Siak Sri Inderapura',
  'Kapal Kato',
  'Masjid Sultan Syarif Hasyim',
  'Taman Tengku Mahratu',
  'Jembatan Tengku Agung Sultanah Latifah',
  'Jembatan Teluk Mesjid',
  'Tepian Bandar Sungai Jantan',
  'Gedung Tangsi Belanda',
  'Klenteng Hock Siu Kiong',
  'Lambang di Alun-alun Maharatu Centre',
  'Danau Zamrud',
  'Lanscape Sawah Bunga Raya',
  'Ekowisata mangrove Mengkapan',
  'Jembatan Kupu Kupu',
  'Balai Kerapatan Tinggi'
    ]
  ],
  'DUM' =>  [
    'name' => 'Pinang Kampai Airport',
    'city' => 'Dumai Sumatra Island',
  ],
  'RKO' =>  [
    'name' => 'Rokot Airport',
    'city' => 'Sipora Island',
  ],
  'SEQ' =>  [
    'name' => 'Sungai Pakning Bengkalis Airport',
    'city' => 'Bengkalis Sumatra Island',
  ],
  'TJB' =>  [
    'name' => 'Sei Bati Airport',
    'city' => 'Tanjung Balai Karinmunbesar Island',
  ],
  'BDO' =>  [
    'name' => 'Husein Sastranegara International Airport',
    'city' => 'Bandung Java Island',
  ],
  'CBN' =>  [
    'name' => 'Penggung Airport',
    'city' => 'Cirebon Java Island',
  ],
  'TSY' =>  [
    'name' => 'Cibeureum Airport',
    'city' => 'Tasikmalaya Java Island',
  ],
  'BTH' =>  [
    'name' => 'Hang Nadim International Airport',
    'city' => 'Batam Island',
    'keys' => [
  'Bukit Senyum',
  'Ocarina Park Batam',
  'Queen Garden Waterboom',
  'Alun-Alun Engku Putri Batam',
  'Pantai Marina Batam',
  'Pantai Vio Vio',
  'Kampung Vietnam',
  'Mata Kucing',
  'Pantai Nongsa Batam',
  'Pantai Mirota',
  'Pulau Abang Besar',
  'Pasar Pagi Jodoh Batam',
  'Nagoya Hill Shopping Mall',
  'Nagoya Citywalk Batam',
  'Lampu Hias Sungai Jodoh',
  'Rumah Kopi Fatmawati',
  'Socialities Crib Batam',
  'Golden Prawn',
  'Harbour Bay Batam',
  'Barelang Bridge'
    ]
  ],
  'PPR' =>  [
    'name' => 'Pasir Pangaraan Airport',
    'city' => 'Pasir Pengarayan Sumatra Island',
  ],
  'TNJ' =>  [
    'name' => 'Raja Haji Fisabilillah International Airport',
    'city' => 'Tanjung Pinang Bintan Island',
    'keys' => [
  'Gurun Pasir Busung',
  'Danau Biru Kawal',
  'Danau Kampung Bloreng',
  'Bukit Panglong Kijang',
  'Bukit Zaitun',
  'Rumah Arang',
  'Masjid Raya Baitul Makmur Tanjung Uban',
  'Kijang City Walk',
  'Hutan Mangrove Kampung Panglong',
  'Batu Junjung',
  'Pantai Panjang',
  'Pantai Senggiling',
  'Pantai Trikora',
  'Pantai Pelangkap',
  'Pantai Lagoi',
  'Pantai Pengudang',
  'Nirwana Beach Club',
  'Serumpun Padi Mas Resort',
  'Pantai Indah Bintan',
  'Pulau Beralas Pasir'
    ]
  ],
  'SIQ' =>  [
    'name' => 'Dabo Airport',
    'city' => 'cgk',
  ],
  'HLP' =>  [
    'name' => 'Halim Perdanakusuma International Airport',
    'city' => 'Jakarta',
  ],
  'CXP' =>  [
    'name' => 'Tunggul Wulung Airport',
    'city' => 'Cilacap Java Island',
  ],
  'PCB' =>  [
    'name' => 'Pondok Cabe Air Base',
    'city' => 'Jakarta',
  ],
  'CGK' =>  [
    'name' => 'Soekarno Hatta International Airport',
    'city' => 'Jakarta',
    'keys' => [
  'Pantai Ancol',
  'Kepulauan Seribu',
  'Pulau Semak Daun',
  'Pulau Tidung',
  'Pulau Bidadari',
  'Pantai Pasir Perawan',
  'Pantai Marunda',
  'Taman Situ Lembang',
  'Taman Cattelya',
  'Taman Ayodya',
  'Taman Hutan Tebet',
  'Hutan Kota Srengseng',
  'Taman Suropati',
  'Taman Menteng',
  'Setu Babakan',
  'Taman Spatodhea',
  'Kebun Binatang Ragunan',
  'Taman Ismail Marzuki',
  'TMII',
  'Taman Pecenongan',
  'Dufan',
  'Ancol',
  'Waterboom Jakarta',
  'Snowbay Waterpark',
  'Ocean Ecopark',
  'Pasar Tanah Abang',
  'Pasar Glodok',
  'Pasar Seni Ancol',
  'Plaza Indonesia',
  'Thamrin City',
  'Museum Taman Prasasti',
  'Museum Satria Mandala',
  'Museum Fatahillah',
  'Museum Tekstil',
  'Museum Bahari',
  'Museum Wayang',
  'Museum Gajah',
  'Monumen Nasional',
  'Masjid Istiqlal',
  'Gereja Katedral',
  'Kelenteng Jin De Yuan',
    ]
  ],
  'TKG' =>  [
    'name' => 'Radin Inten II [Branti] Airport',
    'city' => 'Bandar Lampung Sumatra Island',
  ],
  'GNS' =>  [
    'name' => 'Binaka Airport',
    'city' => 'Gunung Sitoli Nias Island',
  ],
  'AEG' =>  [
    'name' => 'Aek Godang Airport',
    'city' => 'Padang Sidempuan Sumatra Island',
  ],
  'MES' =>  [
    'name' => 'Soewondo Air Force Base',
    'city' => 'Medan Sumatra Island',
  ],
  'KNO' =>  [
    'name' => 'Kualanamu International Airport',
    'city' => '',
    'keys' => [
  'Danau Toba',
  'Sipinsur',
  'Menara Pandang Tele',
  'Danau Siombak',
  'Istana Maimun',
  'Tjong A Fie Mansion',
  'Maha Vihara Adhi Maitreya',
  'Graha Maria Annai Velangkanni',
  'Masjid Raya Medan',
  'Taman Labirin',
  'Rahmat International Wildlife Museum & Gallery',
  'Gedung London Sumatera',
  'Funland Mickey Holiday',
  'Sipisopiso',
  'Savana Afrika',
  'Gedung Balai Kota Lama',
  'Kebun Binatang Medan',
  'Penangkaran Buaya Asam Kumbang',
  'Hairos Water Park',
  'Wonders Water World',
  'Arung Jeram Sungai Bingei',
  'Pantai Mangrove',
  'The Le Hu Garden',
  'Kampung Ladang',
  'Merci Barn',
  'Air Terjun Dua Warna',
  'Hillpark Sibolangit',
  'The Garden Cafe',
  'Royal Sumatera',
  'Resep Nenek Moyangku',
  'Lekker Urban Food House',
  'Desadesa Resto',
  'Gardenia Tropical Garden Resto',
  'The Edge Restaurant',
  'Ismud Park',
  'Stage Cafe',
  'Sosmed Cafe',
  'Sam Bistro & Lounge',
  'Pasar Belawan',
  'Kawasan Souvenir Jalan Ahmad Yani'
    ]
  ],
  'DTB' =>  [
    'name' => 'Silangit Airport',
    'city' => 'Siborong Borong',
  ],
  'SIW' =>  [
    'name' => 'Sibisa Airport',
    'city' => 'Parapat Sumatra Island',
  ],
  'FLZ' =>  [
    'name' => 'Dr Ferdinand Lumban Tobing Airport',
    'city' => 'Sibolga Sumatra Island',
  ],
  'TJQ' =>  [
    'name' => 'H.AS. Hanandjoeddin International Airport',
    'city' => 'Tanjung Pandan Belitung Island',
  ],
  'NPO' =>  [
    'name' => 'Nanga Pinoh Airport',
    'city' => 'Nanga Pinoh Borneo Island',
  ],
  'KTG' =>  [
    'name' => 'Ketapang[Rahadi Usman] Airport',
    'city' => 'Ketapang Borneo Island',
  ],
  'MWK' =>  [
    'name' => 'Tarempa Airport',
    'city' => 'Matak Island',
  ],
  'NTX' =>  [
    'name' => 'Ranai Airport',
    'city' => 'Ranai Natuna Besar Island',
  ],
  'PNK' =>  [
    'name' => 'Supadio Airport',
    'city' => 'Pontianak Borneo Island',
    'keys' => [
  'Pantai Kijing',
  'Taman Alun-Alun Kapuas',
  'Tugu Khatulistiwa',
  'Tugu Digulis',
  'Aloe Vera Centre',
  'Hutan Kota Untan',
  'Keraton Kesultanan Kadriah',
  'Rumah Betang Radakng',
  'Museum Kalimantan Barat',
  'Masjid Jami Pontianak',
  'Masjid Raya Mujahidin',
  'Makam Kesultanan Pontianak',
  'Pantai Pasir Panjang',
  'Pantai Kura-Kura',
  'Pantai Batu Burung',
  'Pantai Sedau',
  'Danau Biru Singkawang',
  'Danau Serantangan',
  'Danau Tadow Indah',
  'Air Terjun Eria',
  'Air Terjun Sibohe',
  'Sinka Island Park',
  'Bukit Rindu Alam',
  'Cagar Alam Raya Pasi',
  'Taman Burung Singkawang',
  'Taman Gayung Bersambut',
  'Taman Cinta Pajintan',
  'Taman Batu Belimbing',
  'Taman Bunga Bukit Bougenvile Singkawang',
  'Waterboom Gunung Poteng',
  'Masjid Raya Singkawang',
  'Tugu Naga Singkawang',
  'Vihara Tri Dharma Bumi Raya',
  'Gereja Katolik Santo Fransiskus Asisi'
    ]
  ],
  'PSU' =>  [
    'name' => 'Pangsuma Airport',
    'city' => 'Putussibau Borneo Island',
  ],
  'SQG' =>  [
    'name' => 'Sintang[Susilo] Airport',
    'city' => 'Sintang Borneo Island',
  ],
  'DJB' =>  [
    'name' => 'Sultan Thaha Airport',
    'city' => 'Jambi Sumatra Island',
  ],
  'BUU' =>  [
    'name' => 'Muara Bungo Airport',
    'city' => 'Muara Bungo',
  ],
  'PGK' =>  [
    'name' => 'Pangkal Pinang [Depati Amir] Airport',
    'city' => 'Pangkal Pinang Palaubangka Island',
  ],
  'BKS' =>  [
    'name' => 'Fatmawati Soekarno Airport',
    'city' => 'Bengkulu Sumatra Island',
  ],
  'PLM' =>  [
    'name' => 'Sultan Mahmud Badaruddin II Airport',
    'city' => 'Palembang Sumatra Island',
    'keys' => [
  'Jembatan Ampera',
  'Masjid Agung Palembang',
  'Masjid Cheng Ho',
  'Masjid Lawang Kidul',
  'Museum Al-Quran Palembang',
  'Pagoda Pulau Kemaro',
  'Benteng Kuto Besak',
  'Museum Sultan Mahmud Badaruddin II',
  'Museum Negeri Balaputra Dewa',
  'Kampung Arab Palembang',
  'Hutan Punti Kayu',
  'Pulau Kemaro',
  'Air Terjun Lematang Indah',
  'Tangga 2001',
  'Tugu Belido',
  'Air Terjun Bidadari',
  'Kebun Teh Dempo',
  'Danau Ranau',
  'Air Terjun Maung',
  'Taman Kambang Iwak',
  'Arung Jeram Sungai Manna',
  'Rumah Rakit Sungai Musi',
  'Bukit Siguntang',
  'Sungai Gerong',
  'Amanzi Water Park',
  'Waterboom OPI Jakabaring',
  'Fantasy Island',
  'Goa Putri',
  'Gunung Dempo',
  'Danau OPI',
  'Taman Purbakala Kerajaan Sriwijaya',
  'Museum Tekstil Palembang',
  'Monuman Perjuangan Rakyat',
  'Tugu Belido',
  'Klenteng Chandra Nadi',
  'Masjid H. Bayumi Wahab',
  'G Art Studio'
    ]
  ],
  'PDO' =>  [
    'name' => 'Pendopo Airport',
    'city' => 'Talang Gudang Sumatra Island',
  ],
  'RGT' =>  [
    'name' => 'Japura Airport',
    'city' => 'Rengat Sumatra Island',
  ],
  'PDG' =>  [
    'name' => 'Minangkabau International Airport',
    'city' => 'Ketaping Padang Sumatra Island',
    'keys' => [
  'Banto Rayo',
  'Masjid Tuo Kayu Jao',
  'Goa Batu Kapal',
  'Pulau Pamutusan',
  'Danau Biru Sawahlunto',
  'Masjid Raya Sumatera Barat',
  'Lawang Adventure Park',
  'Wisata Alam Tonang',
  'Ngalau Simarasok',
  'Puncak Gagoan',
  'Air Terjun Lubuk Hitam',
  'Pulau Siburu',
  'Danau Maninjau',
  'Air Terjun Langkuik Tinggi',
  'Jembatan Akar Bayang',
  'Danau Singkarak',
  'Kota Tua Padang',
  'Tabiang Takuruang',
  'Air Terjun Bayang Sani',
  'Air Terjun Lambah Anai',
  'Ngarai Sianok Bukittinggi',
  'Green House Lezata Bukittinggi',
  'Danau Kembar Sumatera Barat'
    ]
  ],
  'MPC' =>  [
    'name' => 'Muko Muko Airport',
    'city' => 'Muko Muko Sumatra Island',
  ],
  'KLQ' =>  [
    'name' => 'Keluang Airport',
    'city' => 'Keluang Sumatra Island',
  ],
  'TPK' =>  [
    'name' => 'Teuku Cut Ali Airport',
    'city' => 'Tapak Tuan Sumatra Island',
  ],
  'SBG' =>  [
    'name' => 'Maimun Saleh Airport',
    'city' => 'Sabang We Island',
  ],
  'MEQ' =>  [
    'name' => 'Seunagan Airport',
    'city' => 'Peureumeue Sumatra Island',
  ],
  'LSX' =>  [
    'name' => 'Lhok Sukon Airport',
    'city' => 'Lhok Sukon Sumatra Island',
  ],
  'LSW' =>  [
    'name' => 'Malikus Saleh Airport',
    'city' => 'Lhok Seumawe Sumatra Island',
  ],
  'BTJ' =>  [
    'name' => 'Sultan Iskandar Muda International Airport',
    'city' => 'Banda Aceh',
  ],
  'ABU' =>  [
    'name' => 'Haliwen Airport',
    'city' => 'Atambua Timor Island',
  ],
  'LKA' =>  [
    'name' => 'Gewayentana Airport',
    'city' => 'Larantuka Flores Island',
  ],
  'SAU' =>  [
    'name' => 'Sabu Tardanu Airport',
    'city' => 'Sabu Sawu Island',
  ],
  'SGQ' =>  [
    'name' => 'Sanggata Sangkimah Airport',
    'city' => 'Sanggata Sangkimah',
  ],
  'LBW' =>  [
    'name' => 'Long Bawan Airport',
    'city' => 'Long Bawan Borneo Island',
  ],
  'BXT' =>  [
    'name' => 'Bontang Airport',
    'city' => 'Bontang Borneo Island',
  ],
  'NNX' =>  [
    'name' => 'Nunukan Airport',
    'city' => 'Nunukan Nunukan Island',
  ],
  'TNB' =>  [
    'name' => 'Tanah Grogot Airport',
    'city' => 'Tanah Grogot Borneo Island',
  ],
  'LPU' =>  [
    'name' => 'Long Apung Airport',
    'city' => 'Long Apung Borneo Island',
  ],
  'SZH' =>  [
    'name' => 'Senipah Heliport',
    'city' => 'Senipah',
  ],
];
